TapNap/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TapNap.Areas.Identity.Data;
using TapNap.Models;

namespace TapNap.Controllers
{
    public class ApiController : Controller
    {
        private readonly TapNapContext _context;
        private readonly UserManager<TapNapUser> _userManager;

        public ApiController(TapNapContext context, UserManager<TapNapUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<JsonResult> GetBeds()
        {
            var data = await _context.Beds
                .Select(b => new
                {
                    id = b.BedID,
                    center = new {lat = b.Latitude, lng = b.Longitude}
                })
                .ToArrayAsync();
            return Json(data);
        }

        public async Task<IActionResult> GetDetails(int? id)
        {
            if (id == null)
                return NotFound();
            
            var bed = await _context.Beds
                .Include(b => b.User)
                .Include(b => b.BedRatings)
                .Include(b => b.Pictures)
                .Where(b => b.BedID == id).Select(b => new
                {
                    pictures = b.Pictures.Select(p => p.Src),
                    rating = Math.Round(b.BedRatings.Select(r => r.Rating).Average(), 2), // at least 1 rating needed
                    price = b.PricePerHour,
                    address = b.Address,
                    description = b.Description,
                    phone = b.User.PhoneNumber
                }).FirstOrDefaultAsync();
            if (bed == null)
                return NotFound();

            return Json(bed);
        }

        public async Task<IActionResult> GetReserved()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound();
            }

            var reserved = await _context.Renteds
                .Include(r => r.Bed).ThenInclude(b => b.User)
                .Include(r => r.Bed).ThenInclude(b => b.Pictures)
                .Where(r => r.UserID == user.Id)
                .Select(r => new{
                    picture = r.Bed.Pictures.First().Src,
                    address = r.Bed.Address,
                    time = $"{r.StartTime:MMM dd h:mm tt} - {r.EndTime:MMM dd h:mm tt}",
                    phone = r.Bed.User.PhoneNumber
                })
                .ToListAsync();

            return Json(reserved);
        }

        public async Task<IActionResult> GetPosts()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound();
            }

            var posts = await _context.Beds
                .Include(b => b.TimePeriods)
                .Include(b => b.Renteds)
                .Include(b => b.BedRatings)
                .Include(b => b.Pictures)
                .Where(b => b.UserID == user.Id)
                .Select(b => new
                {
                    pictures = b.Pictures.Select(p => p.Src),
                    //rating = b.BedRatings.Select(r => r.Rating).Average(), // at least 1 rating needed
                    price = b.PricePerHour,
                    address = b.Address,
                    description = b.Description,
                    times = b.TimePeriods.Select(t => $"{t.StartTime:MMM dd h:mm tt} - {t.EndTime:MMM dd h:mm tt}")
                })
                .ToListAsync();

            return Json(posts);
        }

        public async Task<IActionResult> AddSelf(int id)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound();
            }

            var bed = await _context.Beds.FindAsync(id);
            if (bed == null)
                return NotFound();

            if (await _context.Renteds.Where(r => r.BedID == id && r.UserID == user.Id).AnyAsync())
                return Ok();

            var reserve = new Rented {Bed = bed, User = user, StartTime = DateTime.Now, EndTime = DateTime.Now.AddHours(1)};
            _context.Add(reserve);
            await _context.SaveChangesAsync();

            return Ok();
        }
    }
}

TapNap/Controllers/BedsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using TapNap.Models;

namespace TapNap.Controllers
{
    public class BedsController : Controller
    {
        private readonly TapNapContext _context;
        private readonly HttpClient Client;

        public BedsController(TapNapContext context)
        {
            _context = context;
            Client = new HttpClient();
            Client.BaseAddress = new Uri("https://api.imgur.com/3/");
            Client.DefaultRequestHeaders.Accept.Clear();
//            Client.DefaultRequestHeaders.Accept.Add(
//                new MediaTypeWithQualityHeaderValue("application/json"));
            Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Client-ID", Startup.ImgurAPI);
        }

        // GET: Beds
        public async Task<IActionResult> Index()
        {
            return View(await _context.Beds.ToListAsync());
        }

        // GET: Beds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bed = await _context.Beds
                .Include(b => b.Pictures)
                .FirstOrDefaultAsync(m => m.BedID == id);
            if (bed == null)
            {
                return NotFound();
            }

            return View(bed);
        }

        // GET: Beds/Create
        public IActionResult Create()
        {
            return View();
        }

        public class BedModel
        {
            public string Address { get; set; }
            public string Description { get; set; }
            public decimal Price { get; set; }
            public List<IFormFile> Files { get; set; }
        }

        // POST: Beds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Bed bed)
        {   
            var rand = new Random();
            var files = Directory.GetFiles("wwwroot/imageAssets/beds", "*.jpg");
            var src = files[rand.Next(files.Length)];
            var pic = new Picture() { Bed = bed, Src= src.Substring(8) };
            bed.Pictures = new[] {pic};

            if (ModelState.IsValid)
            {
                _context.Add(bed);
                await _context.SaveChangesAsync();
//                var pictures = new List<Picture>();
//                foreach (var file in bed.Files)
//                {
//                    var newPicture = new Picture() { Bed = newBed };
//                    var stream = file.OpenReadStream();
//                    var form = new MultipartFormDataContent();
//                    var content = new StreamContent(stream);
//                    form.Add(content);
//                    var response = await Client.PostAsJsonAsync("image", form);
//                    var responseContent = await response.Content.ReadAsStringAsync();
//                    var details = JObject.Parse(responseContent);
//                    var temp = details["data"]["link"];
//                    //TODO: might be broken
//                    newPicture.Src = (string)temp;
//                    pictures.Add(newPicture);
//                }
//
//                _context.AddRange(pictures);
//                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            
            return View(bed);
        }

        // GET: Beds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bed = await _context.Beds.FindAsync(id);
            if (bed == null)
            {
                return NotFound();
            }



            return View(bed);
        }

        // POST: Beds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BedID,Address,Description,PricePerHour")] Bed bed, TimePeriod time)
        {
            if (id != bed.BedID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bed);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BedExists(bed.BedID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bed);
        }

        // GET: Beds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bed = await _context.Beds
                .FirstOrDefaultAsync(m => m.BedID == id);
            if (bed == null)
            {
                return NotFound();
            }

            return View(bed);
        }

        // POST: Beds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bed = await _context.Beds.FindAsync(id);
            _context.Beds.Remove(bed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BedExists(int id)
        {
            return _context.Beds.Any(e => e.BedID == id);
        }
    }
}

TapNap/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TapNap.Models;

namespace TapNap.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TapNap/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TapNap.Areas.Identity.Data;
using TapNap.Models;

namespace TapNap.Controllers
{
    public class ReservationController : Controller
    {
        private readonly TapNapContext _context;
        private readonly UserManager<TapNapUser> _userManager;

        public ReservationController(TapNapContext context, UserManager<TapNapUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public class Reservation
        {
            public int id { get; set; }
            public string picture { get; set; }
            public string address { get; set; }
            public string time { get; set; }
            public string phone { get; set; }
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return View(null);
            }

            var reserved = await _context.Renteds
                .Include(r => r.Bed).ThenInclude(b => b.User)
                .Include(r => r.Bed).ThenInclude(b => b.Pictures)
                .Where(r => r.UserID == user.Id)
                .Select(r => new Reservation
                {
                    picture = r.Bed.Pictures.First().Src,
                    address = r.Bed.Address,
                    time = $"{r.StartTime:MMM dd h:mm tt} - {r.EndTime:MMM dd h:mm tt}",
                    phone = r.Bed.User.PhoneNumber,
                    id = r.Bed.BedID
                })
                .ToListAsync();

            return View(reserved);
        }
    }
}

TapNap/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

TapNap/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TapNap/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE HTML>
<html>
<head>
    <link href="styles.css" rel="stylesheet">
    <link href="mapStyles.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="slicktheme.css"/>
    <link rel="stylesheet" type="text/css" href="rateit-js/rateit.css"/>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.28.7/dist/sweetalert2.all.min.js"></script>

    <meta content="text/html; charset=UTF-8" http-equiv="content-type">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

<div class="navbar-background">
    <div class="navbar-top-segment">
        <div class="segment left-segment">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="logo">Tap N' Nap</a>
            <div class="segment-item">
                <a asp-area="" asp-controller="Reservation" asp-action="Index">Current Naps</a>
            </div>
            <!-- <div class="segment-item"><a asp-area="" asp-controller="Home" asp-action="Contact">Perspective</a></div> -->
            <div class="segment-item">
                <input type="text" class="searchbar" id="searchbar-top" placeholder="Search for a bed">
            </div>
            <div id="add-listing" class="segment-item add-listing-button">
                <div>
                    ADD LISTING
                </div>
            </div>
        </div>
        <div class="segment right-segment">
            <partial name="_LoginPartial" />
        </div>
    </div>

    <div class="navbar-mobile-segment">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="logo">Tap N' Nap</a>
        <img src="imageAssets/hamburger.svg" id="navbar-hamburger">
    </div>
</div>

<div class="hide" id="hide">
    <div class="navigation-mobile-screen navigation-mobile-screen-side">
        <div class="segment-item mobile-nav-first">
            <a asp-area="" asp-controller="Reservation" asp-action="Index">Current Naps</a>
        </div>
        <!-- <div class="segment-item"><a asp-area="" asp-controller="Home" asp-action="Contact">Perspective</a></div> -->
        <div class="segment-item">
            <input type="text" class="searchbar" id="searchbar-mobile" placeholder="Search for a bed">
        </div>
        <partial name="_LoginPartial" />
    </div>
</div>

<div class="map-container">
    <div id="map"></div>
    <div class="listing-information">
        <img id="listing-exit" src="imageAssets/close-button.png">
        <div class="slider">
            <div>
                <div class="slider-image-wrapper">
                    <img id="image1" class="slider-image" src="imageAssets/bed_example.jpg">
                </div>
            </div>
            <div>
                <div class="slider-image-wrapper">
                    <img id="image2" class="slider-image" src="imageAssets/bed_example.jpg">
                </div>
            </div>
        </div>
        <div class="listing-information-text">
            <div class="listing-address" id="listing-address">
                710 East 21st Street, Austin, Texas
            </div>
            <div id="rateit" class="rateit" data-rateit-mode="font" data-rateit-readonly="true" data-rateit-step="0.1" data-rateit-value="4.3"></div>
            <div class="rating-text" id="rating-text">
                Overall Rating: 4.3
            </div>
            <div class="listing-title" id="listing-title">
                Private Bedroom
            </div>
            <div class="listing-description" id="listing-description">
                Experience calm in this bright, private apartment perched in the hills with awe-inspiring views. Enjoy yourself, or others, on the luxurious, 2000-sheet silk sheets covering a genuine Moroccan cotton mattress.
            </div>
            <div class="listing-pricing">
                <span class="fancy-pricing-text" id="listing-pricing">$10</span> / HOUR
            </div>
            <div class="book-button" id="book-button">
                <div>
                    RESERVE NOW
                </div>
            </div>
        </div>
    </div>
</div>

<form style="visibility: hidden" action='@Url.Action("Create", "Beds")' method="post" id="add-listing-form">
    <input id="latitude" type="hidden">
    <input id="longitude" type="hidden">
    <input id="title" type="hidden">
    <input id="price" type="hidden">
    <input id="rating" type="hidden">
</form>

<div class="footer">
</div>


<script src="mapLoad.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAxYh2EnW1d4ldOte-dAp9DVJYL1UVAGw4&callback=initMap&libraries=places"
        async defer></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
<script type="text/javascript" src="rateit-js/jquery.rateit.js"></script>

<script type="text/javascript">
    function verify() {
        swal({
            type: 'success',
            title: "<span class='sweet-font'>Listing Successfully Created!</span>",
            html: "<span class='sweet-font'>Be sure to edit your listing to include all relevant details!</span>",
            confirmButtonText: "Awesome, got it!"
        });
        return true;
    }

    $(document).ready(function() {

        document.getElementById("listing-exit").addEventListener('click', hideInfo);
        document.getElementById("navbar-hamburger").addEventListener('click', toggle);
        document.getElementById("book-button").addEventListener('click', function () { showPhoneNumber() });
        document.getElementById("add-listing").addEventListener('click', addListing);

        $('.slider').slick({
            infinite: true,
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows: true,
        });

    });

    function addListing() {
        swal({
            title: '<span class="sweet-font-form">Finish adding your listing!</span>',
            html:
                '<input id="form-title" class="swal2-input" placeholder="Property Title">' +
                    '<input id="form-price" class="swal2-input" placeholder="Property Pricing">',
            confirmButtonText: "Add my room!",
            focusConfirm: false,
            preConfirm: () => {
                let areaObject = map.getBounds();
                document.getElementById("latitude").value = (areaObject.f.b + areaObject.f.f) / 2;
                document.getElementById("longitude").value = (areaObject.b.b + areaObject.b.f) / 2;
                document.getElementById("title").value = document.getElementById("form-title").value;
                document.getElementById("price").value = document.getElementById("form-price").value;
                document.getElementById("rating").value = Math.floor((Math.random() * 3) + 2) + 0.1 * Math.floor(Math.random() * 11);

                   // TODO: Fix submission!!
//                document.getElementById("add-listing-form").submit();
//                $(function() {
//                    $('#add-listing-form').submit(function(){
//                        $.post('http://example.com/upload', function() {
//                            window.location = 'http://google.com';
//                        });
//                        return false;
//                    });
//                });
                // TODO: FORM SUBMISSION LOGIC


                // console.log(document.getElementById("latitude").value);
                // console.log(document.getElementById("longitude").value);
                // console.log(document.getElementById("title").value);
                // console.log(document.getElementById("price").value);
                // console.log(document.getElementById("rating").value);
            }
        }).then((result) => {
            if (result.value) {
                swal({
                    type: 'success',
                    title: "<span class='sweet-font'>Listing successfully added!</span>",
                    confirmButtonText: "<a href='/beds'>Check out my listings!</a>"
                });
            }
        });
    }

    function showPhoneNumber(id) {
        fetch('@Url.Action("AddSelf", "Api")' + `?id=${id}`)
            .then(function(response) {
                return response.json();
            })
            .then(function(myJson) {
                // Do nothing
                // console.log(JSON.stringify(myJson));
            });

        swal({
            type: 'info',
            title: "<span class='sweet-font'>Host's Phone Number</span>",
            html: "<span class='sweet-font'>(111)-222-3333</span>",
            confirmButtonText: "Awesome, got it!"
        });

        hideInfo();
    }

    function hideInfo() {
        document.getElementById("listing-exit").parentElement.classList.remove("show-listing-information");
    }

    function toggle(event) {
        if (document.getElementsByClassName("navigation-mobile-screen")[0].classList.contains(
            "navigation-mobile-screen-side")) {
            document.getElementById("hide").style.position = "static";
            setTimeout(function() {
                    document.getElementsByClassName("navigation-mobile-screen")[0].classList.remove(
                        "navigation-mobile-screen-side");
                },
                1);
        } else {
            document.getElementsByClassName("navigation-mobile-screen")[0].classList.add(
                "navigation-mobile-screen-side");
            setTimeout(function() {
                    document.getElementById("hide").style.position = "relative";
                },
                250);
        }
    }
</script>

</body>
</html>